from manager.job_registry import job
from utils.db import with_db_select

import asyncio

@job(name="db_select_example")
@with_db_select("SELECT id, name FROM users")
async def print_users(rows):
    for row in rows:
        print(dict(row))
        await asyncio.sleep(0.5)
        
#CREATE TABLE 
# CREATE TABLE users (
#     id SERIAL PRIMARY KEY,
#     name TEXT,
#     email TEXT
# );

# INSERT INTO users (name, email) VALUES
# ('Alice Kim', 'alice.kim1@example.com'),
# ('Bob Park', 'bob.park2@example.com'),
# ('Charlie Lee', 'charlie.lee3@example.com'),
# ('Diana Choi', 'diana.choi4@example.com'),
# ('Ethan Jung', 'ethan.jung5@example.com'),
# ('Fiona Han', 'fiona.han6@example.com'),
# ('George Lim', 'george.lim7@example.com'),
# ('Hannah Yoo', 'hannah.yoo8@example.com'),
# ('Ian Kwon', 'ian.kwon9@example.com'),
# ('Jenna Song', 'jenna.song10@example.com'),
# ('Kevin Hwang', 'kevin.hwang11@example.com'),
# ('Laura Shin', 'laura.shin12@example.com'),
# ('Mike Ahn', 'mike.ahn13@example.com'),
# ('Nina Jang', 'nina.jang14@example.com'),
# ('Oscar Ryu', 'oscar.ryu15@example.com'),
# ('Pam Lee', 'pam.lee16@example.com'),
# ('Quincy Park', 'quincy.park17@example.com'),
# ('Rachel Kim', 'rachel.kim18@example.com'),
# ('Steve Moon', 'steve.moon19@example.com'),
# ('Tina Jung', 'tina.jung20@example.com'),
# ('Ursula Seo', 'ursula.seo21@example.com'),
# ('Victor Baek', 'victor.baek22@example.com'),
# ('Wendy Kang', 'wendy.kang23@example.com'),
# ('Xavier Cho', 'xavier.cho24@example.com'),
# ('Yuna Hwang', 'yuna.hwang25@example.com'),
# ('Zack Koo', 'zack.koo26@example.com'),
# ('Amy Bae', 'amy.bae27@example.com'),
# ('Brian Choi', 'brian.choi28@example.com'),
# ('Cathy Lim', 'cathy.lim29@example.com'),
# ('Daniel Yoo', 'daniel.yoo30@example.com'),
# ('Eva Han', 'eva.han31@example.com'),
# ('Frank Kim', 'frank.kim32@example.com'),
# ('Grace Lee', 'grace.lee33@example.com'),
# ('Henry Park', 'henry.park34@example.com'),
# ('Irene Moon', 'irene.moon35@example.com'),
# ('Jason Shin', 'jason.shin36@example.com'),
# ('Kelly Ahn', 'kelly.ahn37@example.com'),
# ('Leo Ryu', 'leo.ryu38@example.com'),
# ('Mia Choi', 'mia.choi39@example.com'),
# ('Nick Jung', 'nick.jung40@example.com'),
# ('Olivia Baek', 'olivia.baek41@example.com'),
# ('Paul Kang', 'paul.kang42@example.com'),
# ('Queenie Seo', 'queenie.seo43@example.com'),
# ('Roy Cho', 'roy.cho44@example.com'),
# ('Sophia Hwang', 'sophia.hwang45@example.com'),
# ('Tom Bae', 'tom.bae46@example.com'),
# ('Una Kwon', 'una.kwon47@example.com'),
# ('Vera Shin', 'vera.shin48@example.com'),
# ('Will Ahn', 'will.ahn49@example.com'),
# ('Xena Ryu', 'xena.ryu50@example.com'),
# ('Aaron Kim', 'aaron.kim51@example.com'),
# ('Bella Lee', 'bella.lee52@example.com'),
# ('Chris Park', 'chris.park53@example.com'),
# ('Daisy Moon', 'daisy.moon54@example.com'),
# ('Edward Hwang', 'edward.hwang55@example.com'),
# ('Faith Seo', 'faith.seo56@example.com'),
# ('Gavin Cho', 'gavin.cho57@example.com'),
# ('Hazel Kang', 'hazel.kang58@example.com'),
# ('Isaac Bae', 'isaac.bae59@example.com'),
# ('Jade Kwon', 'jade.kwon60@example.com'),
# ('Kurt Shin', 'kurt.shin61@example.com'),
# ('Lily Ahn', 'lily.ahn62@example.com'),
# ('Max Ryu', 'max.ryu63@example.com'),
# ('Nora Choi', 'nora.choi64@example.com'),
# ('Owen Jung', 'owen.jung65@example.com'),
# ('Penny Baek', 'penny.baek66@example.com'),
# ('Quentin Kang', 'quentin.kang67@example.com'),
# ('Rita Seo', 'rita.seo68@example.com'),
# ('Sean Cho', 'sean.cho69@example.com'),
# ('Terry Hwang', 'terry.hwang70@example.com'),
# ('Uma Kwon', 'uma.kwon71@example.com'),
# ('Vicky Lee', 'vicky.lee72@example.com'),
# ('Warren Park', 'warren.park73@example.com'),
# ('Ximena Moon', 'ximena.moon74@example.com'),
# ('Yuri Kim', 'yuri.kim75@example.com'),
# ('Zane Han', 'zane.han76@example.com'),
# ('Allie Choi', 'allie.choi77@example.com'),
# ('Ben Lim', 'ben.lim78@example.com'),
# ('Cara Yoo', 'cara.yoo79@example.com'),
# ('Derek Han', 'derek.han80@example.com'),
# ('Ella Kim', 'ella.kim81@example.com'),
# ('Felix Lee', 'felix.lee82@example.com'),
# ('Gina Park', 'gina.park83@example.com'),
# ('Howard Moon', 'howard.moon84@example.com'),
# ('Isabel Hwang', 'isabel.hwang85@example.com'),
# ('Jack Seo', 'jack.seo86@example.com'),
# ('Kim Cho', 'kim.cho87@example.com'),
# ('Luna Baek', 'luna.baek88@example.com'),
# ('Mason Kang', 'mason.kang89@example.com'),
# ('Nina Kwon', 'nina.kwon90@example.com'),
# ('Omar Shin', 'omar.shin91@example.com'),
# ('Paula Ahn', 'paula.ahn92@example.com'),
# ('Quinn Ryu', 'quinn.ryu93@example.com'),
# ('Rose Choi', 'rose.choi94@example.com'),
# ('Sam Jung', 'sam.jung95@example.com'),
# ('Tara Baek', 'tara.baek96@example.com'),
# ('Ugo Kang', 'ugo.kang97@example.com'),
# ('Vince Seo', 'vince.seo98@example.com'),
# ('Willa Cho', 'willa.cho99@example.com'),
# ('Xander Hwang', 'xander.hwang100@example.com');

